name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t node-app .

    - name: Copy files to Azure VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        port: 22
        source: "."
        target: "~/node-app"

    - name: Deploy on Azure VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        port: 22
        script: |
          cd ~/node-app
          docker stop node-app || true
          docker rm node-app || true
          docker build -t node-app .
          docker run -d -p 3000:3000 --name node-app node-app
